spring:
  application:
    name: access-management-service
  cloud:
    config:
      label: main
  config:
    import: optional:configserver:http://config-server:8888
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}    

